services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webcms-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_PATH=${FRONTEND_PATH}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - webcms-network
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: webcms-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webcms-network

volumes:
  postgres-data:

networks:
  webcms-network:
    driver: bridge
